export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const GET_AUTHORS = 'GET_AUTHORS';
export const LOADING_AUTHORS = 'LOADING_AUTHORS';
export const LOADING_AUTHORS_SUCCESS = 'LOADING_AUTHORS_SUCCESS';
export const LOADING_AUTHORS_ERROR = 'LOADING_AUTHORS_ERROR';

export const FETCH_PUBLICATIONS = 'FETCH_PUBLICATIONS';
export const GET_PUBLICATIONS = 'GET_PUBLICATIONS';
export const LOADING_PUBLICATIONS = 'LOADING_PUBLICATIONS';
export const LOADING_PUBLICATIONS_SUCCESS = 'LOADING_PUBLICATIONS_SUCCESS';
export const LOADING_PUBLICATIONS_ERROR = 'LOADING_PUBLICATIONS_ERROR';

export const ENABLE_DRAG = 'ENABLE_DRAG';
export const DISABLE_DRAG = 'DISABLE_DRAG';
